CREATE DATABASE proyecto_HDP_EFECTO_DEL_SALARIO_MINIMO;

USE proyecto_HDP_EFECTO_DEL_SALARIO_MINIMO;

CREATE TABLE Consultas (
    id INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(100) NOT NULL,
    correo_electronico NVARCHAR(100) NOT NULL,
    telefono NVARCHAR(15),
    comentario NVARCHAR(MAX) NOT NULL,
    fecha_envio DATETIME DEFAULT GETDATE()
);

